test code scanning mode

diff --git a/.github/workflows/codeql-analysis-with-atm-query-suite.yml b/.github/workflows/codeql-analysis-with-atm-query-suite.yml
--- a/.github/workflows/codeql-analysis-with-atm-query-suite.yml
+++ b/.github/workflows/codeql-analysis-with-atm-query-suite.yml
@@ -7,9 +7,10 @@ on:
   workflow_dispatch:
 
 env:
-  BASE_URL: 'https://atmcodeqlpublicdata.blob.core.windows.net/atmpublic/query-suite/v1.0.0-rc1+368448f'
-  CLI_ADDITIONS_CHECKSUM: 'cd1225fa4a61c35b9dd51e3324df4facdb9633d0a86de7be636d1225ccf88713e04a1501bdc2f23b0313224396163eb0113185fdf59fcc35207cc72f1afb9bda'
-  QLPACK_CHECKSUM: 'd88295e6ffb20d64eb458f984ef2fb0b9ab6ef4dd3f2a5f5d778444c77cc919e402b72a97bd7fd201424be081c25f9e9795e796b84f7a0985ffb0ab45d385fe7'
+  BASE_URL: 'https://atmcodeqlpublicdata.blob.core.windows.net/atmpublic/query-suite/v1.0.1+a6aa602'
+  CLI_ADDITIONS_CHECKSUM: '6375e05e0326966e27bec63db61a92e56ebb563fe1aa67adc13c0262cbca55d7ddb6d13d5bd63c169b95b2cbe7cea5e5c560346c4302738724311a463735ef44'
+  MODEL_CHECKSUM: 'f0191c93957ccdfa27059c37ac08897f57e80e9660507dfbf40d826c13e78fd4'
+  QLPACK_CHECKSUM: 'a39bd8d90cfa39bf4f8a2c42481d7d22f3e04cc89451bde8eac98cc77688d3b42d6e9cc876e97314671c72c0d6d7a1405d6105202eb6377123b55ea188b6fac6'
 
 jobs:
   CodeQL-Build:
@@ -29,32 +30,24 @@ jobs:
               "$(sha512sum -b qlpack.tar.gz | awk '{ print $1 }')"
             exit 1
           fi
-
           mkdir -p .github/codeql
           atm_qlpack_path=".github/codeql/codeql-javascript-atm"
           mkdir ${atm_qlpack_path}
           tar -xvzf qlpack.tar.gz -C ${atm_qlpack_path}
           rm qlpack.tar.gz
-
           ls -lR ${atm_qlpack_path}
-
           # Add ATM query pack to the CodeQL search path
           CODEQL_CONFIG_FILE="${RUNNER_TEMP}/codeql_config"
           echo "CODEQL_CONFIG_FILE=${CODEQL_CONFIG_FILE}" >> ${GITHUB_ENV}
           echo "--search-path ${atm_qlpack_path}" >> ${CODEQL_CONFIG_FILE}
-
           echo "ATM CodeQL CLI config file contents:"
           cat ${CODEQL_CONFIG_FILE}
-
           echo "name: \"ATM CodeQL config\"" > .github/codeql/codeql-config.yml
           echo "disable-default-queries: true" >> .github/codeql/codeql-config.yml
           echo "queries:" >> .github/codeql/codeql-config.yml
           echo "  - uses: ./${atm_qlpack_path}/codeql-suites/javascript-atm-code-scanning.qls" >> .github/codeql/codeql-config.yml
-
           echo "ATM Code Scanning config file contents:"
           cat .github/codeql/codeql-config.yml
-
-
       # Initializes the CodeQL tools for scanning.
       - name: Initialize CodeQL
         id: codeql-init
@@ -71,7 +64,6 @@ jobs:
         run: |
           cli_root="$(dirname ${CODEQL_PATH})"
           echo "Using CodeQL CLI root at ${cli_root}"
-
           cli_additions_url="${BASE_URL}/codeql-atm-cli-additions.tar.gz"
           echo "Attempting to download ATM CLI additions from ${cli_additions_url}"
           azcopy10 cp "${cli_additions_url}" cli-additions.tar.gz
@@ -80,16 +72,20 @@ jobs:
               "$(sha512sum -b cli-additions.tar.gz | awk '{ print $1 }')"
             exit 1
           fi
-
           tar -xvzf cli-additions.tar.gz -C ${cli_root}
           rm cli-additions.tar.gz
-
           ls -lR ${cli_root}/lib-extra
           ls -lR ${cli_root}/ml-models
           
           echo "Model properties:"
           cat ${cli_root}/ml-models/*.qlmodel/model.properties
-
+          echo "Checking that the model checksum matches the expected one defined in the 'env'" \
+            "property of the workflow definition"
+          if ! grep -q "checksum=${MODEL_CHECKSUM}" ${cli_root}/ml-models/*.qlmodel/model.properties; then
+            echo "::error::Failed to validate ATM model checksum. Expected checksum=${MODEL_CHECKSUM}, was" \
+              "$(grep 'checksum' ${cli_root}/ml-models/*.qlmodel/model.properties)"
+            exit 1
+          fi
       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v1
         with:
